# -*- coding: utf-8 -*-
"""
Type stubs for native_statistics compiled extension.
"""

from typing import Any, Dict, Optional

STATISTICS_AVAILABLE: bool

class StreamingMetricHandle:
    """Native streaming statistics handle."""

    def __init__(self, window_size: int = 1440) -> None: ...
    def update(self, value: float) -> None: ...
    def extend(self, values: Any) -> None: ...
    def reset(self) -> None: ...
    def snapshot(self) -> Dict[str, Optional[float]]: ...

    @property
    def window_size(self) -> int: ...

    def __len__(self) -> int: ...

def create_streaming_metric(window_size: int = 1440) -> StreamingMetricHandle: ...
