# -*- coding: utf-8 -*-
"""Type stubs for vnpy_paperaccount package."""

from typing import Any

class PaperAccountEngine:
    """Paper Account Engine class stub."""
    def __init__(self, event_engine: Any) -> None: ...
    def init_engine(self) -> None: ...
    def set_capital(self, capital: float) -> None: ...
    def set_parameters(
        self,
        commission_rate: float = 0.0,
        slippage: float = 0.0,
        size: int = 1
    ) -> None: ...
    def close(self) -> None: ...
    def send_order(self, req: Any) -> str: ...
    def cancel_order(self, req: Any) -> None: ...

def __getattr__(name: str) -> Any: ...  # noqa: U100
