# -*- coding: utf-8 -*-
"""
Type stubs for native_finance_ops compiled extension.
"""

from typing import Any, Dict, List, Tuple

FINANCE_OPS_AVAILABLE: bool
VERSION: str

def apply_price_adjustments(*args, **kwargs) -> Any: ...
def aggregate_daily_pnl(*args, **kwargs) -> Dict[str, Any]: ...
def compute_return_metrics(pnl_series: List[float], equity_series: List[float], trading_days_per_year: int = 252) -> Dict[str, Any]: ...
def bucketize_period(*args, **kwargs) -> Dict[str, Any]: ...
def compute_period_statistics(dates: List[str], pnl: List[float], initial_equity: float = 1000000.0, risk_free_rate: float = 0.03, trading_days_per_year: int = 252) -> Dict[str, Any]: ...
def compute_risk_profile(returns: List[float], scale: float = 1.0, risk_free_rate: float = 0.03, trading_days_per_year: int = 252, confidence_levels: List[float] = ...) -> Dict[str, Any]: ...
